// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/questions.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 111140041067501049),
      name: 'Questions',
      lastPropertyId: const obx_int.IdUid(6, 245746567519042835),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6456741016786169556),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2837077454669326733),
            name: 'text',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7179262142441625899),
            name: 'option1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8080751696656937501),
            name: 'option2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8343267460646288390),
            name: 'option3',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 245746567519042835),
            name: 'correctAnswer',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 111140041067501049),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Questions: obx_int.EntityDefinition<Questions>(
        model: _entities[0],
        toOneRelations: (Questions object) => [],
        toManyRelations: (Questions object) => {},
        getId: (Questions object) => object.id,
        setId: (Questions object, int id) {
          object.id = id;
        },
        objectToFB: (Questions object, fb.Builder fbb) {
          final textOffset = fbb.writeString(object.text);
          final option1Offset = fbb.writeString(object.option1);
          final option2Offset = fbb.writeString(object.option2);
          final option3Offset = fbb.writeString(object.option3);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, textOffset);
          fbb.addOffset(2, option1Offset);
          fbb.addOffset(3, option2Offset);
          fbb.addOffset(4, option3Offset);
          fbb.addInt64(5, object.correctAnswer);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final textParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final option1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final option2Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final option3Param = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final correctAnswerParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = Questions(
              id: idParam,
              text: textParam,
              option1: option1Param,
              option2: option2Param,
              option3: option3Param,
              correctAnswer: correctAnswerParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Questions] entity fields to define ObjectBox queries.
class Questions_ {
  /// See [Questions.id].
  static final id =
      obx.QueryIntegerProperty<Questions>(_entities[0].properties[0]);

  /// See [Questions.text].
  static final text =
      obx.QueryStringProperty<Questions>(_entities[0].properties[1]);

  /// See [Questions.option1].
  static final option1 =
      obx.QueryStringProperty<Questions>(_entities[0].properties[2]);

  /// See [Questions.option2].
  static final option2 =
      obx.QueryStringProperty<Questions>(_entities[0].properties[3]);

  /// See [Questions.option3].
  static final option3 =
      obx.QueryStringProperty<Questions>(_entities[0].properties[4]);

  /// See [Questions.correctAnswer].
  static final correctAnswer =
      obx.QueryIntegerProperty<Questions>(_entities[0].properties[5]);
}
